[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312', 'py313']
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
known_django = ["django"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
order_by_type = true  # Organize by type within sections
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = true
use_parentheses = true
