# Generated by Django 4.2.17 on 2024-12-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O +ve', 'O_POS'), ('O -ve', 'O_NEG'), ('A +ve', 'A_POS'), ('A -ve', 'A_NEG'), ('B +ve', 'B_POS'), ('B -ve', 'B_NEG'), ('AB +ve', 'AB_POS'), ('AB -ve', 'AB_NEG')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='drinking_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='smoking_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='substance_abuse_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
