# Generated by Django 4.2.17 on 2025-06-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
