# Generated by Django 4.2.17 on 2025-06-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_facility', '0003_roomoccupancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomoccupancy',
            options={'ordering': ['-end_date'], 'verbose_name': 'Room Occupancy', 'verbose_name_plural': 'Room Occupancies'},
        ),
    ]
