# Generated by Django 4.2.17 on 2025-01-03 08:31

import phonenumber_field.modelfields

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('first_name', 'middle_name', 'last_name', 'email')},
        ),
    ]
