# Generated by Django 4.2.17 on 2025-01-07 06:40

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("ayuh_patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_registration_id",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
