# Generated by Django 4.2.17 on 2025-01-03 08:31

from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'middle_name', 'last_name', 'email')},
        ),
    ]
