# Generated by Django 4.2.17 on 2025-05-24 10:38

from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ("ayuh_patient", "0002_alter_patientprofile_primary_physician_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientprofile",
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
            },
        ),
    ]
