# Generated by Django 4.2.17 on 2025-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_patient', '0003_alter_patientprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('SEARCH', 'search'), ('ACQUAINTANCE', 'Acquaintance'), ('NEWSPAPER', 'Newspaper'), ('TELEVISION', 'TV'), ('RADIO', 'Radio'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('X', 'X')], default='', null=True),
        ),
    ]
