# Generated by Django 4.2.17 on 2024-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_patient', '0003_remove_patient_emergency_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='drinking_status',
            field=models.CharField(blank=True, choices=[('Never', 'NEVER'), ('Occasional', 'OCCASIONAL'), ('Regular', 'REGULAR'), ('Heavy', 'HEAVY')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Never', 'NEVER'), ('Occasional', 'OCCASIONAL'), ('Regular', 'REGULAR'), ('Heavy', 'HEAVY')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='substance_abuse_status',
            field=models.CharField(blank=True, choices=[('Never', 'NEVER'), ('Occasional', 'OCCASIONAL'), ('Regular', 'REGULAR'), ('Heavy', 'HEAVY')], default='', null=True),
        ),
    ]
