# Generated by Django 4.2.17 on 2025-03-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'medicine', 'verbose_name_plural': 'medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicinebatch',
            options={'verbose_name': 'medicine batch', 'verbose_name_plural': 'medicine batches'},
        ),
        migrations.AlterModelOptions(
            name='medicinemanufacturer',
            options={'verbose_name': 'medicine manufacturer', 'verbose_name_plural': 'medicine manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='medicinepurchase',
            options={'verbose_name': 'medicine purchase', 'verbose_name_plural': 'medicine purchases'},
        ),
        migrations.AlterModelOptions(
            name='medicinesale',
            options={'verbose_name': 'medicine sale', 'verbose_name_plural': 'medicine sales'},
        ),
        migrations.AlterModelOptions(
            name='medicinestock',
            options={'verbose_name': 'medicine stock', 'verbose_name_plural': 'medicine stocks'},
        ),
        migrations.AlterModelOptions(
            name='medicinesupplier',
            options={'verbose_name': 'medicine supplier', 'verbose_name_plural': 'medicine suppliers'},
        ),
    ]
