# Generated by Django 4.2.17 on 2025-05-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicinemanufacturer',
            options={'verbose_name': 'Medicine Manufacturer', 'verbose_name_plural': 'Medicine Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='medicinepurchase',
            options={'verbose_name': 'Medicine Purchase', 'verbose_name_plural': 'Medicine Purchases'},
        ),
        migrations.AlterModelOptions(
            name='medicinesale',
            options={'verbose_name': 'Medicine Sale', 'verbose_name_plural': 'Medicine Sales'},
        ),
        migrations.AlterModelOptions(
            name='medicinesaleitem',
            options={'verbose_name': 'Medicine Sale Item', 'verbose_name_plural': 'Medicine Sale Items'},
        ),
        migrations.AlterModelOptions(
            name='medicinestock',
            options={'verbose_name': 'Medicine Stock', 'verbose_name_plural': 'Medicine Stocks'},
        ),
    ]
