# Generated by Django 4.2.17 on 2025-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_inventory', '0002_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.CharField(blank=True, choices=[('ARISHTAM', 'Arishtam'), ('CHOORNAM', 'Choornam'), ('GHRTAM', 'Ghrtam'), ('GULIKA', 'Gulika'), ('KASHAAYAM', 'Kashaayam'), ('LEPAM', 'Lepam'), ('LEHYAM', 'Lehyam'), ('THAILAM', 'Thailam')], default='', null=True),
        ),
    ]
