# Generated by Django 4.2.17 on 2025-05-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_inventory', '0003_alter_medicine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ayuh_inventory.medicine'),
        ),
    ]
