# Generated by Django 4.2.17 on 2025-05-24 14:13

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("ayuh_patient", "0003_alter_patientprofile_options"),
        ("ayuh_inventory", "0004_alter_medicinestock_medicine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinesaleitem",
            name="patient",
        ),
        migrations.AddField(
            model_name="medicinesale",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ayuh_patient.patient",
            ),
        ),
    ]
