# Generated by Django 4.2.17 on 2025-05-25 11:17

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("ayuh_inventory", "0005_remove_medicinesaleitem_patient_medicinesale_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicinesale",
            name="customer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
