# Generated by Django 4.2.17 on 2025-07-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_inventory', '0008_remove_medicinesalepaymentinfo_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinesalepaymentinfo',
            name='gst_on_consultation_fee',
        ),
        migrations.RemoveField(
            model_name='medicinesalepaymentinfo',
            name='total_consultation_amount_with_gst',
        ),
        migrations.AlterField(
            model_name='medicinesalepaymentinfo',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'card'), ('CASH', 'cash'), ('UPI', 'upi'), ('OTHER', 'other')], default='', null=True),
        ),
    ]
