# Generated by Django 4.2.17 on 2025-06-07 09:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ayuh_staff", "0001_initial"),
        ("ayuh_consultation", "0007_alter_consultation_patient_concerns_onset_from"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ayuh_facility", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treatment_overview", models.TextField(blank=True, null=True)),
                ("patient_notes", models.TextField(blank=True, null=True)),
                ("doctor_notes", models.TextField(blank=True, null=True)),
                ("treatment_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "by_stander_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "by_stander_contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region="IN"
                    ),
                ),
                ("admission_date", models.DateTimeField(auto_now_add=True)),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_consultation",
                        to="ayuh_consultation.consultation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ayuh_facility.room",
                    ),
                ),
                (
                    "treatment_updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="the user who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("treatment", models.TextField(blank=True, null=True)),
                ("treatment_date", models.DateField()),
                ("treatment_feedback", models.TextField(blank=True, null=True)),
                (
                    "admission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_admission",
                        to="ayuh_admission.admission",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        blank=True,
                        db_column="doctor",
                        limit_choices_to={"designation": "Therapist"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_therapist",
                        to="ayuh_staff.staff",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "bulk_change",
                    "bulk_delete",
                    "bulk_add",
                    "export",
                ),
            },
        ),
    ]
