# Generated by Django 4.2.17 on 2025-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_admission', '0002_alter_admission_options_admission_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
