# Generated by Django 4.2.17 on 2025-07-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_admission', '0003_treatment_treatment_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='treatment_cost',
            new_name='treatment_amount',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_feedback',
        ),
    ]
