# Generated by Django 4.2.17 on 2024-12-16 12:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("ayuh_patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_person_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="IN"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="IN"
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="primary_care_provider",
            field=models.CharField(
                blank=True,
                db_comment="Name of the Clinic/Hospital which the patient goes to",
                max_length=255,
                null=True,
            ),
        ),
    ]
