services:
  api:
    platform: ${PLATFORM}
    build:
      context: .
    image: ${IMAGE_NAME}
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - .:/narayaneeyam
    ports:
      - "8000:8000"
    networks:
      - backend_network
    depends_on:
      - local_postgres

  local_postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

volumes:
  postgres_data:


networks:
  backend_network:
    driver: bridge