services:
  api:
    platform: ${PLATFORM:-linux/amd64}
    build:
      context: .
    image: ${IMAGE_NAME:-narayaneeyam:latest}
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-ayuh.settings}
    volumes:
      - .:/narayaneeyam
    ports:
      - "8000:8000"
    networks:
      - backend_network
    depends_on:
      - local_postgres

  local_postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-narayaneeyam}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network


volumes:
  postgres_data:


networks:
  backend_network:
    driver: bridge