# Generated by Django 4.2.17 on 2025-01-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_consultation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_prescription', to='ayuh_consultation.consultation'),
        ),
    ]
