# Generated by Django 4.2.17 on 2025-04-21 07:12

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("ayuh_consultation", "0004_alter_consultationattachment_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
