# Generated by Django 4.2.17 on 2025-06-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_consultation', '0005_prescription_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='doctors_comments',
            new_name='doctor_comments',
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ongoing_medications_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_concerns_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_concerns_onset_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
