# Generated by Django 4.2.17 on 2025-06-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayuh_consultation', '0006_rename_doctors_comments_consultation_doctor_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient_concerns_onset_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
